version: "3"

services:
  farming:
    container_name: wanxinp2p-file-service
    build: .
    image: wanxinp2p-file-service:1.0-SNAPSHOT
    network_mode: "host"
    ports:
      - "56082:56082"
    restart: always
    depends_on:
      - redis
    volumes:
      - "./logs:/logs"
    environment:
      JAVA_OPTS: "-Xms256m -Xmx256m -Xmn128m"