server:
  port: 59000
  servlet:
    context-path: /sentinel
spring:
  application:
    name: SentinelDemo
  cloud:
    sentinel:
      transport:
        # 设置 dashboard 的地址
        dashboard: localhost:9898
