server:
  port: 59022
  servlet:
    context-path: /service-b
spring:
  application:
    name: feign-hystrix-service-b
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:59020/eureka/