version: "3"

services:
  apollo-configservice: # 容器服务名
    container_name: apollo-configservice # 容器名
    build: apollo-configservice/ # Dockerfile路径
    image: apollo-configservice:1.6.0 # 镜像名
    network_mode: "host"
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "./logs/100003171:/opt/logs/100003171"    # 将/opt/logs/100003171目录挂载到宿主机的./logs/100003171方便在宿主机上查看日志
    environment:
      spring_datasource_url: "jdbc:mysql://127.0.0.1:3306/ApolloConfigDB?characterEncoding=utf8"
      spring_datasource_username: "root"
      spring_datasource_password: "123456"
      JAVA_OPTS: "-Xms512m -Xmx512m -Xmn256m"

  apollo-adminservice:
    container_name: apollo-adminservice
    build: apollo-adminservice/
    image: apollo-adminservice:1.6.0
    network_mode: "host"
    ports:
      - "8090:8090"
    restart: always
    depends_on:
      - apollo-configservice
    volumes:
      - "./logs/100003172:/opt/logs/100003172"
    environment:
      spring_datasource_url: "jdbc:mysql://127.0.0.1:3306/ApolloConfigDB?characterEncoding=utf8"
      spring_datasource_username: "root"
      spring_datasource_password: "123456"
      JAVA_OPTS: "-Xms512m -Xmx512m -Xmn256m"

  apollo-portal:
    container_name: apollo-portal
    build: apollo-portal/
    image: apollo-portal:1.6.0
    network_mode: "host"
    ports:
      - "8070:8070"
    restart: always
    depends_on:
      - apollo-adminservice
    volumes:
      - "./logs/100003173:/opt/logs/100003173"
    environment:
      spring_datasource_url: "jdbc:mysql://127.0.0.1:3306/ApolloPortalDB?characterEncoding=utf8"
      spring_datasource_username: "root"
      spring_datasource_password: "123456"
      JAVA_OPTS: "-Xms512m -Xmx512m -Xmn256m -Ddev_meta=http://127.0.0.1:8080"