version: '3'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4.14
    restart: always
    ports:
      - 21811:2181
    logging:
      driver: "json-file"
      options:
        max-size: "10k"
        max-file: "10"