version: '3'
services:
  logstash:
    container_name: logstash
    build: ./
    image: docker.elastic.co/logstash/logstash:6.2.4
    volumes:
      - './config/logstash.yml:/usr/share/logstash/config/logstash.yml'
      - './pipeline:/usr/share/logstash/pipeline'
      - './config/wanxinp2p_project_template.json:/usr/share/logstash/config/wanxinp2p_project_template.json'
      - './sql:/usr/share/logstash/sql'
      - './logstash_metadata:/usr/share/logstash/config/logstash_metadata'
    network_mode: "host"
    restart: "always"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      TZ: "Asia/Shanghai"